### PR TITLE
feat(tutorials): add colab link for each tutorial

### PR DESCRIPTION
**Pull request by Benjamin-eecs**
## Description

Add colab link for all tutorials.

## Checklist

- [x] I have read the [CONTRIBUTION](https://github.com/facebookresearch/rl/blob/main/CONTRIBUTING.md) guide (**required**)

### CODE REVIEW

**Comment by vmoens** [comment]
Thanks for this. I'm almost done re-running the tutorials right now. I was about to add the links in there. Can I ask you to review it when it's done?

How can we make it so that when executing the code on collab the packages are readily available?

**Comment by Benjamin-eecs** [comment]
> Can I ask you to review it when it's done?

Yeah, for sure. I'd love to.

> How can we make it so that when executing the code on collab the packages are readily available?

I am not sure I get it, but if you mean that whether we can have a colab link where the code is synced with the notebook copy in the github repo. There is a trick to get the colab for each tutorial: take [coding_ddpg.ipynb](https://github.com/facebookresearch/rl/blob/main/tutorials/coding_ddpg.ipynb) for an example, where the link of the tutorial is `https://github.com/facebookresearch/rl/blob/main/tutorials/coding_ddpg.ipynb`, you can simply add a 'tocolab' after the `github` and make it `https://githubtocolab.com/facebookresearch/rl/blob/main/tutorials/coding_ddpg.ipynb`. And it pops out the corresponding colab link. Wondering if that's your want to do with the colab link?

**Comment by vmoens** [comment]
It's more like: how do you install torchrl on Google collab?

**Comment by Benjamin-eecs** [comment]
> It's more like: how do you install torchrl on Google collab?

I think add `!pip install torchrl` will be enough? (Of course the dependencies can be written in the similar form) Unless you want users to try the tutorial with torchrl building from source.

**Comment by vmoens** [comment]
Good idea!

**Pull request closed without merging**
