### PR TITLE
[Feature] Replaced prints by warnings in gym envs

### PR DESCRIPTION
**Pull request by nicolas-dufour**
## Description

Replaced warnings by prints in gym

## Checklist

Go over all the following points, and put an `x` in all the boxes that apply.
If you are unsure about any of these, don't hesitate to ask. We are here to help!

- [x] I have read the [CONTRIBUTION](https://github.com/facebookresearch/rl/blob/main/CONTRIBUTING.md) guide (**required**)

### CODE REVIEW

**Comment by vmoens** [comment]
Can you give some context about why we need this?
I prefer warnings, they only appear once and they have a dedicated purpose

**Comment by nicolas-dufour** [comment]
It's a change that was made in dreamer. I don't really know why

**Comment by vmoens** [comment]
Ok probably something I thought was a good idea haha
If you don't mind I'd suggest to stick to warnings and close this

**Comment by nicolas-dufour** [comment]
Wait but don't you prefer to have warnings? Right now the code has prints

**Pull request closed without merging**
