### PR TITLE
[Feature] Add all implemented loggers to the init of loggers

### LINKED ISSUE #349: [BUG] Loggers registration
## Describe the bug

The [`__init__.py`](https://github.com/facebookresearch/rl/blob/main/torchrl/trainers/loggers/__init__.py) from loggers does not reference the implemented loggers. However, the [docstring from the trainer](https://github.com/facebookresearch/rl/blob/806733f27dfa9a878b75b079de9f18df83f54c2d/torchrl/trainers/helpers/trainers.py#L109) assumes that this kind of import can be run.

### PR DESCRIPTION
**Pull request by flinder**
## Description

Adds all implemented loggers to `trainers.logger.__init__.py`

## Motivation and Context

close #349 

## Types of changes

What types of changes does your code introduce? Remove all that do not apply:

- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist

Go over all the following points, and put an `x` in all the boxes that apply.
If you are unsure about any of these, don't hesitate to ask. We are here to help!

- [x ] I have read the [CONTRIBUTION](https://github.com/facebookresearch/rl/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by vmoens — APPROVED** [review]
LGTM, thanks for this
Let's just wait until the CI is fixed and tests pass, then we'll land this :)

**Comment by vmoens** [comment]
> LGTM, thanks for this Let's just wait until the CI is fixed and tests pass, then we'll land this :)

You can merge the PR I created, that should fix the tests!

**Comment by flinder** [comment]
> > LGTM, thanks for this Let's just wait until the CI is fixed and tests pass, then we'll land this :)
> 
> You can merge the PR I created, that should fix the tests!

Thanks for fixing this so quickly. I don't have write access though, so can't merge PRs

**Comment by vmoens** [comment]
No I meant on your fork there's a PR from myself

**Comment by flinder** [comment]
> No I meant on your fork there's a PR from myself. Otherwise you can just merge main from torchrl onto your branch

oh sorry, somehow missed that one. I merged it

**Comment by vmoens** [comment]
Fantastic, thanks to your contribution we've found a bug in the tests.
In `test_trainer.py` we were importing `TensorboardLogger` from `from torchrl.trainers.loggers` which resulted in an error => the `_has_tb` was always False and all the tests that requires `TensorboardLogger` were silently ignored.

I would suggest to amend your PR with the two following changes: 
(1) Even with your edit I think it would make more sense to import `TensorboardLogger` from its original file and not `torchrl.trainers.loggers` in `test_trainer.py`
(2) We can fix this bug by simply adding `args.collector_devices = ["cpu"]`

**Review by vmoens — APPROVED** [review]
LGreatTM!
Don't worry about the failing OSX test, we just need to wait for a millisecond between two operations to make sure that the tensorboard thread has done its job... 
It's a flacky test that needs to be fixed.

**Pull request merged**
