### PR TITLE
[Feature]: `TensorDictPrimer` transform

### PR DESCRIPTION
**Pull request by nicolas-dufour**
## Description

This PR add a ForceTensorReset transform.

## Motivation and Context

ForceTensorReset allows to set or reset to default values some given vectors
## Types of changes

What types of changes does your code introduce? Remove all that do not apply:

- [x] New feature (non-breaking change which adds core functionality)

## Checklist

Go over all the following points, and put an `x` in all the boxes that apply.
If you are unsure about any of these, don't hesitate to ask. We are here to help!

- [x] I have read the [CONTRIBUTION](https://github.com/facebookresearch/rl/blob/main/CONTRIBUTING.md) guide (**required**)
- [x] My change requires a change to the documentation.
- [x] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by vmoens** [comment]
Lint!

**Comment by vmoens** [comment]
`ForceTensorReset` is not very indicative IMO
What about 
- `DefaultTensorRest`
- `DefaultValueReset`
- `TensorDictPrimerReset`
- `TensorDictPrimer`
- `TensorDictPrimerTransform`

**Comment by vmoens** [comment]
Added `TensorDictPrimer`
Let me know if that's a suitable solution. The big advantage is that the spec is registered in the env, and we can execute rollouts in parallel without problem as the tensordict will be properly pre-allocated.
If you're fine with it, can you remove `ForceTensorReset` as well as the tests?
You can rename the class if you feel like it :)

**Comment by nicolas-dufour** [comment]
The transform is still needed to properly reset the states. Thank you for the changes to rollout!. I'll rename it to DefaultTensorReset if that's ok with you

**Comment by vmoens** [comment]
Have you looked at my solution? It does reset things. What does ForceTensorReset do that TensorDictPrimer does not?

**Comment by nicolas-dufour** [comment]
I'm not sure i understand how i can set vectors that aren't given by the env with TensorDictPrimer. Like prior_state and belief

**Comment by vmoens** [comment]
Look at the docstring :)

**Comment by nicolas-dufour** [comment]
Ah it's with the kwargs. Ok i will remove my tests and transform then

**Pull request merged**
