### PR TITLE
[Logging]: implement MLFlow logging integration

### LINKED ISSUE #395: [Feature Request] Integrate MLFlow in the loggers backends
## Motivation

MLFlow would be a nice-to-have in our loggers.

## Solution

The essential features of loggers are (as of now) add_scalar and add_video.
I'm not sure if MLFlow supports videos, but if not I guess that storing it as an artifact would work? 

Note:
The split between runs and experiment is a nice to have. I suspect that integrating this with hydra won't be easy with our current config API, which is quite flat and assumed that all loggers have the same params. I suspect that this will be refactored soon, but as of now we can assume that all loggers have an experiment and run attribute.

## Tests
Tests should be implemented for the logger, with specific tests for each logging capability. See [test/test_loggers.py](https://github.com/facebookresearch/rl/blob/main/test/test_loggers.py) for context.

To test this feature, one should be able to run
```bash
python ppo.py logger=mlflow
```

### PR DESCRIPTION
**Pull request by rayanht**
## Description

This diff enables torchrl to seamlessly use the MLFlow Tracking API through its internal `Logger` API. These changes are consistent with previous integrations such as the one with W&B.

A test suite for the new integration has been included in the diff.

## Motivation and Context

close #395

## Types of changes

What types of changes does your code introduce? Remove all that do not apply:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds core functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)
- [ ] Example (update in the folder of examples)

## Checklist

Go over all the following points, and put an `x` in all the boxes that apply.
If you are unsure about any of these, don't hesitate to ask. We are here to help!

- [x] I have read the [CONTRIBUTION](https://github.com/facebookresearch/rl/blob/main/CONTRIBUTING.md) guide (**required**)
- [ ] My change requires a change to the documentation.
- [x] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by rayanht** [comment]
Just realised I need to update the examples to add a case for the MLFlow logger

**Comment by rayanht** [comment]
Alright so running:

```
$ python ppo.py logger=mlflow
```

We get the following generated directory:

Screenshot 2022-09-14 at 14 34 30


Which we can then point the mlflow UI to using:

```
$ mlflow ui --backend-store-uri ppo_logging
```

Screenshot 2022-09-14 at 14 36 17

Screenshot 2022-09-14 at 14 36 37

Unfortunately MLFlow doesn't support the preview of video files but there's nothing we can do about that.

**Review by vmoens — APPROVED** [review]
Absolutely wonderful, thanks for this!
Before landing: Can we add mlflow to the packages installed in the CI (linux and linux_stable)?

**Comment by rayanht** [comment]
I'm investigating the test failure, might have something to do with how directories are managed in my implementation.

**Comment by vmoens** [comment]
> I'm investigating the test failure, might have something to do with how directories are managed in my implementation.

Let me know if I can help!

**Comment by rayanht** [comment]
@vmoens I can't repro the test failure locally, is there any way we can get get the full log on Circle CI? rn I'm not even sure what package is failing to import because the stacktrace is cut off:

```
FAILED test/test_loggers.py::TestMLFlowLogger::test_log_video[None] - ImportE... <---- 
FAILED test/test_loggers.py::TestMLFlowLogger::test_log_video[steps1] - Excep...
=== 2 failed, 8079 passed, 170 skipped, 7914 warnings in 1349.69s (0:22:29) ====
```

**Comment by vmoens** [comment]
There are 2 errors

1.
```
test/test_loggers.py::TestMLFlowLogger::test_log_video[None] FAILED      [ 38%]
____________________ TestMLFlowLogger.test_log_video[None] _____________________
Traceback (most recent call last):
  File "/home/circleci/project/test/test_loggers.py", line 148, in test_log_video
    logger.log_video(
  File "/home/circleci/project/torchrl/trainers/loggers/mlflow.py", line 109, in log_video
    torchvision.io.write_video(filename=f.name, video_array=video, fps=fps)
  File "/home/circleci/project/env/lib/python3.8/site-packages/torchvision/io/video.py", line 83, in write_video
    _check_av_available()
  File "/home/circleci/project/env/lib/python3.8/site-packages/torchvision/io/video.py", line 42, in _check_av_available
    raise av
ImportError: PyAV is not installed, and is necessary for the video operations in torchvision.
See https://github.com/mikeboers/PyAV#installation for instructions on how to
install PyAV on your system.
```

This can be solved by adding `av` to the pip section of `environment.yaml` in the `.circleci` folders (not in the one with opt deps of course).


2.
```
test/test_loggers.py::TestMLFlowLogger::test_log_video[steps1] FAILED    [ 38%]
___________________ TestMLFlowLogger.test_log_video[steps1] ____________________
Traceback (most recent call last):
  File "/home/circleci/project/test/test_loggers.py", line 139, in test_log_video
    logger = MLFlowLogger(exp_name=exp_name, tracking_uri=log_dir_uri)
  File "/home/circleci/project/torchrl/trainers/loggers/mlflow.py", line 56, in __init__
    super().__init__(exp_name=exp_name, log_dir=tracking_uri)
  File "/home/circleci/project/torchrl/trainers/loggers/common.py", line 23, in __init__
    self.experiment = self._create_experiment()
  File "/home/circleci/project/torchrl/trainers/loggers/mlflow.py", line 69, in _create_experiment
    return mlflow.start_run(experiment_id=self.id)
  File "/home/circleci/project/env/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 271, in start_run
    raise Exception(
Exception: Run with UUID 8d99f1ba38d6419584647c3ef8f21026 is already active. To start a new run, first end the current run with mlflow.end_run(). To start a nested run, call start_run with nested=True
```
This is probably due to a failure to close the session in the previous test.
What we should do is use pytest to make sure that `mlflow.end_run()` is called at the end of the function, see [this](https://stackoverflow.com/a/52873379) for an example or [this](https://stackoverflow.com/a/39401087).

**Comment by rayanht** [comment]
Cool will amend, thanks! Out of curiosity did you manage to repro locally or did I miss something on the Circle CI UI?

**Comment by vmoens** [comment]
I just looked at the errors, I did not try it locally

**Pull request merged**
